workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.neoland.dungeonidle"
      xcode: latest
      node: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS app
        script: |
          xcodebuild build -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Debug \
            -derivedDataPath build/ios \
            -arch arm64 \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/ios/Build/Products/Debug-iphoneos/*.app
