workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.neoland.dungeonidle"
      xcode: latest
      node: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install Capacitor sync
        script: |
          npx capacitor sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install --repo-update
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild build \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -derivedDataPath build \
            -arch arm64 \
            -sdk iphoneos \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          cd ../..
    artifacts:
      - ios/App/build/Build/Products/Debug-iphoneos/App.app
